Repository sparta-USD/Na-dle-Front, pull requests merged in 2022-11, with the labels that each got.

#6 Design: 공용 base부분 Spotify처럼 UI 업데이트
  index.html
  static/css/style.css
Labels: bug, enhancement

#9 Design: 메인페이지UI 구현 #7
  index.html
  static/css/main.css
  static/css/style.css
Labels: enhancement

#11 Design: Profile UI 구현
  profile.html
  static/css/profile.css
  static/css/style.css
Labels: enhancement

#21 Feat: 메인화면 API 통신 구현 #19
  index.html
  static/css/style.css
  static/js/mainAPI.js
Labels: enhancement

#36 Feat: 회원가입 페이지 API #35
  .gitignore
  login.html
  signup.html
  static/js/signup.js
Labels: enhancement

#42 Feat: 선호도 조사 API, Front-End 기능 구현 및 디자인 수정 #17
  first_like.html
  static/js/first_like.js
Labels: enhancement

#44 Feat : 음원 상세페이지 - 음원 정보, 리뷰 작성/수정/삭제
  first_like.html
  music_detail.html
  static/css/music_detail.css
  static/js/music_detail.js
Labels: enhancement

#38 Feat: 로그인 페이지 API #37
  signin.html
  static/js/signin.js
Labels: enhancement

#45 Fix : 음악 전체 목록페이지 링크 및 총평점 누락 수정
  index.html
  music_list.html
  static/js/mainAPI.js
  static/js/music.js
Labels: bug

#47 Feat: music_card 총평점, 로그인한 유저만 접근가능하게 처리
  index.html
  static/js/mainAPI.js
Labels: enhancement

#50 Feat : 내 프로필페이지 Username 안넣을 경우 로그인한 유저 정보 출력
  static/js/profile.js
  static/js/signin.js
Labels: bug, enhancement

#52 Fix : 음원상세페이지로 이동하는 url을 입력할 때 예외처리 + Feat : 음원 상세정보에 총평점 보여주기
  music_detail.html
  static/css/music_detail.css
  static/js/music_detail.js
Labels: enhancement

#54 Feat: 첫 로그인일 경우만 선호도조사 페이지로 이동 #53
  first_like.html
  profile.html
  static/css/style.css
  static/js/first_like.js
  static/js/profile.js
  static/js/signin.js
Labels: enhancement

#55 Feat: profile.html 팔로우 API를 모달과 연결 
  profile.html
  static/css/profile.css
  static/css/style.css
  static/js/profile.js
Labels: enhancement

#56 Fix: profile.html 팔로우를 API브런치 merge 후 생긴 버그 해결 
  static/css/profile.css
  static/js/profile.js
Labels: bug

#57 Feat : Back-end API 연결
  .gitignore
  first_like.html
  index.html
  music_detail.html
  music_list.html
  profile.html
  profile_edit.html
  review.html
  signin.html
  signup.html
  static/css/music_detail.css
  static/css/profile.css
  static/css/review.css
  static/css/style.css
  static/js/first_like.js
  static/js/logout.js
  static/js/mainAPI.js
  static/js/music.js
  static/js/music_detail.js
  static/js/profile.js
  static/js/profile_edit.js
  static/js/signin.js
  static/js/signup.js
Labels: enhancement
